### ISSUE TITLE
typescript-build-linker: Consider supporting jsonc rather than json

### ISSUE THREAD

**Issue by ericcrosson-bitgo** [typescript-tools/typescript-tools#34]
So we support the same format that the TypeScript compiler uses.

Downsides:
- extra package and all the vulns that come with it

Upsides:
- less surprises

**Comment by EricCrosson** [comment]
How about: allow reading in jsonc (does this handle the trailing-comma case?) but always write JSON

**Comment by EricCrosson** [comment]
Closing in advance of deprecation, this ticket is immaterial
